# Generated by Django 5.2 on 2025-04-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_customer_store_custo_last_na_e6a359_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customer",
            name="store_custo_last_na_e6a359_idx",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="first_name",
            new_name="given_name",
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["last_name", "given_name"],
                name="store_custo_last_na_bf90f6_idx",
            ),
        ),
    ]
