# Generated by Django 5.2 on 2025-04-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_customer_store_custo_last_na_bf90f6_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL(""" 
        INSERT INTO store_collection(title)
        VALUES('collection1')                          
        """, """ 
            DELETE FROM store_collection
            WHERE title='collection1'
            """)
    ]
